-- TradingCoreOS Streamlit deployment schema
-- Run this once in the SQL Editor for the configured Supabase project.
-- The app uses Postgres tables rather than Storage because time-series records
-- need upserts, filtering, and Realtime delivery.

create table if not exists tradingcore_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null,
  capture_minute timestamptz not null,
  trading_date date not null,
  index_name text not null,
  spot numeric,
  expiry text,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (index_name, capture_minute)
);

create index if not exists tradingcore_snapshots_index_minute_idx
  on tradingcore_snapshots (index_name, capture_minute desc);

create table if not exists live_ticks (
  id bigint generated by default as identity primary key,
  symbol text not null,
  ts timestamptz not null,
  price numeric not null,
  previous_close numeric,
  created_at timestamptz not null default now()
);

create index if not exists live_ticks_symbol_ts_idx
  on live_ticks (symbol, ts desc);

create table if not exists price_candles (
  id bigint generated by default as identity primary key,
  symbol text not null,
  trading_date date not null,
  ts text not null,
  open numeric,
  high numeric,
  low numeric,
  close numeric,
  volume numeric,
  created_at timestamptz not null default now(),
  unique (symbol, ts)
);

-- Only the browser needs to read live ticks. All writes are made by the
-- Streamlit server using SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
alter table tradingcore_snapshots enable row level security;
alter table live_ticks enable row level security;
alter table price_candles enable row level security;

drop policy if exists "live ticks browser select" on live_ticks;
create policy "live ticks browser select"
  on live_ticks for select to anon using (true);

alter table live_ticks replica identity full;

do $$
begin
  alter publication supabase_realtime add table live_ticks;
exception
  when duplicate_object then null;
end $$;
